app = "task-manager-frontend"
primary_region = "iad" # Same region as backend for low latency

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[env]
  # Add frontend-specific environment variables, e.g., API base URL
  VITE_API_URL = "https://task-manager-backend.fly.dev" # Backend app URL