app = "task-manager-backend"
primary_region = "iad" # Choose your preferred region

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[env]
  # Add environment variables as needed, e.g., DATABASE_URL
  PORT = "8000"

[deploy]
  release_command = "python init_db.py" # Run database initialization if needed